# This is a basic workflow that is manually triggered

name: Build and Publish Docker Image

on:
  push:
    branches:
      - main

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Build and push Docker images
        uses: docker/build-push-action@v2.9.0
        with:
          github-token: ${{ secrets.DOCKER_PERSONAL_ACCESS_TOKEN }}
